mysite/account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'),
    url(r"^login/$", auth_views.login, name="user_login"),
    url(r"^new-login/$", auth_views.login, {"template_name": "account/login.html"}),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name="user_register"),
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"account/password-change-done"}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password-reset/$', auth_views.password_reset, {"template_name":"account/password_reset_form.html", "email_template_name":"account/password_reset_email.html",  "post_reset_redirect":"/account/password-reset-done"}, name="password_reset"),
    url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name":"account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, {"template_name":"account/password_reset_confirm.html", "post_reset_redirect":"/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete, {"template_name":"account/password_reset_complete.html"}, name="password_reset_complete"),
    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

#"subject_template_name":"account/password_reset_subject.txt", 

mysite/article/urls.py
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"), 
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

mysite/course/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView   
from .views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, CreateLessonView, ListLessonsView, DetailLessonView
from .views import StudentListLessonView

urlpatterns = [
    #url(r'about/$', TemplateView.as_view(template_name="course/about.html")),   
    url(r'about/$', AboutView.as_view(), name="about"),    
    url(r'course-list/$', CourseListView.as_view(), name="course_list"),
    url(r'manage-course/$', ManageCourseListView.as_view(), name="manage_course"),
    url(r'create-course/$', CreateCourseView.as_view(), name="create_course"),
    url(r'delete-course/(?P<pk>\d+)/$', DeleteCourseView.as_view(), name="delete_course"),
    url(r'create-lesson/$', CreateLessonView.as_view(), name="create_lesson"),
    url(r'list-lessons/(?P<course_id>\d+)/$', ListLessonsView.as_view(), name="list_lessons"),
    url(r'detail-lesson/(?P<lesson_id>\d+)/$', DetailLessonView.as_view(), name="detail_lesson"),
    url(r'lessons-list/(?P<course_id>\d+)/$', StudentListLessonView.as_view(), name="lessons_list"),
]

mysite/image/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-images/$', views.list_images, name="list_images"),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^del-image/$', views.del_image, name='del_image'),
    url(r'^images/$', views.falls_images, name="falls_images"),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.flatpages import views
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace='account', app_name='account')),
    url(r'^pwd_reset/', include("password_reset.urls", namespace='pwd_reset', app_name='pwd_reset')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^image/', include('image.urls', namespace='image', app_name='image')),
    url(r'^course/', include('course.urls', namespace='course', app_name='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
        	{% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascritp %}{% endblock %}
    </body>
</html>

mysite/templates/footer.html
<div class="container">
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
	</div>
	<div>
	    <ul class="nav navbar-nav" role="navigation">
		<li><a href="{% url 'home' %}">HOME</a></li>
		<li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
                <li><a href="{% url 'course:about' %}">关于本站</a></li>
	    </ul>
	    <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
		{% if user.is_authenticated %}
		<li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username }}<span class='caret'></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div>
                </li>
		<li><a href="{% url 'account:user_logout' %}">Logout</a></li>
		{% else %}
		<li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
		{% endif %}
	    </ul>
	</div>
    </nav>
</div>
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

mysite/templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
<div class="text-center">
    <h1>WELCOM YOU</h1>
    <h3>Life is short. You need Python</h3>
    <h2>Django makes it easier to build better Web apps more quickly and with less code.</h2>
    {% load staticfiles %}
    <img src="{% static 'images/book.jpg' %}">
</div>
{% endblock %}

mysite/templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}    
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>